### PR TITLE
Allow user to erase classes from option more easily

### LINKED ISSUE #319: Allow user to erase classes from option more easily
We should provide a way for the user to more easily erase classes from options instead of having them have to go one 
by one and removing the selection.

Assigned to Rodrigo

### PR DESCRIPTION
**Pull request by racoelhosilva**
### Erase classes easily

Added a button that erases all selected classes in the current option.
Design is based on the button from the CoursePicker modal.

##### (after approval) closes #319

### CODE REVIEW

**Review by jose-carlos-sousa — CHANGES_REQUESTED** [review]
Nice work  :)  .  I have only one small concern I have noticed that if I choose one option, lock it and then I click the "limpar" button that option will be empty and locked without the possibility of unlocking. Imo one easy solution would be to add "locked: false" to each course option.
Screenshot from 2024-11-17 23-57-10
Screenshot from 2024-11-17 23-57-21

**Comment by racoelhosilva** [comment]
> Nice work :) . I have only one small concern I have noticed that if I choose one option, lock it and then I click the "limpar" button that option will be empty and locked without the possibility of unlocking. Imo one easy solution would be to add "locked: false" to each course option. Screenshot from 2024-11-17 23-57-10 Screenshot from 2024-11-17 23-57-21

First of all, thank you and thanks for the suggestion. 
I hadn't tested erasing classes with locked classes, but I think it makes sense to clear and unlock all classes when the button is clicked. I already added that fix.
I also noticed that the filtered teachers are not reset, but I believe the behavior is better like this since there is already a reset teachers button.
If you have have any other suggestions, please share them :)

**Review by tomaspalma — CHANGES_REQUESTED** [review]
Great work! :rocket: 

I just have one small thing to point out. I don't think it makes sense for the "Limpar" button to be visible when there is no class chosen in the current `selectedOption` entry inside the `multipleOptions` array.

I believe you just have to check if all of the entries inside `multipleOptions[selectedOption].course_options` are null and if so don't show the button

image

**Comment by tomaspalma** [comment]
> I also noticed that the filtered teachers are not reset, but I believe the behavior is better like this since there is already a reset teachers button.

I also agree with that

**Comment by jose-carlos-sousa** [comment]
> Great work! 🚀
> 
> I just have one small thing to point out. I don't think it makes sense for the "Limpar" button to be visible when there is no class chosen in the current `selectedOption` entry inside the `multipleOptions` array.
> 
> I believe you just have to check if all of the entries inside `multipleOptions[selectedOption].course_options` are null and if so don't show the button
> 
> image

To be honest, I don’t see an issue with this approach. It makes the layout more consistent, as it avoids frequently removing and re-adding the "Limpar" button. While clearing all options when none are selected might seem unnecessary, having the option available still makes sense for consistency and usability. Additionally, there are similar examples in tts—for instance, when selecting course units, the "Limpar" button remains visible even if no course units are selected.

**Comment by tomaspalma** [comment]
> Additionally, there are similar examples in tts—for instance, when selecting course units, the "Limpar" button remains visible even if no course units are selected.

That is no longer the case since PR #336 was merged into develop.

I agree that it is worse for consistency, but I don't think the changes will be that frequent since the "Limpar" button will not be one of the main things the users will be interacting with while choosing classes.

**Comment by jose-carlos-sousa** [comment]
> > Additionally, there are similar examples in tts—for instance, when selecting course units, the "Limpar" button remains visible even if no course units are selected.
> 
> That is no longer the case since PR #336 was merged into develop.
> 
> I agree that it is worse for consistency, but I don't think the changes will be that frequent since the "Limpar" button will not be one of the main things the users will be interacting with while choosing classes.

I wasn’t referring to the "Remover Seleção" button; I was referring to the actual "Limpar" button in the CoursePicker. The "Remover Opção" button is fine because the user doesn’t actively see it disappearing—initially it isn't there, then you select an option and the next time you go there , the button appears.

However, with the "Limpar" button, it would appear and disappear in front of the user. While this might not happen very often and may not be a significant issue, I’m still more inclined to leave it as it is.

**Comment by tomaspalma** [comment]
I've decided to agree wtih you @jose-carlos-sousa 

The "remover seleção" were occupying useful space in the dropdown so that's why they were removed. 

However, this is not occupying that much space and will not be there for very long as the users will start choosing course units right away

**Review by jose-carlos-sousa — APPROVED** [review]
LGTM :)  :rocket:

**Pull request merged**
