### PR TITLE
fix: sometimes class options were not always shown

### LINKED ISSUE #286: Not displaying option
"Mestrado em Estudos de Arte" -> "CMC - Conceitos de Museologia Contemporâ..."

Is you select the dropdown, no option is show, but using the random fill, it displays an option. For some reason, it is not showing in the dropdown

### PR DESCRIPTION
**Pull request by tomaspalma**
Closes #286 and #288 

Besides fixing the problem when there are classes in an uc but those are not shown on the dropdown, below are the ways that we show to the user that there are no professors or options.

## Desktop

image

2024-09-08-22:55:42-screenshot

## Mobile

image

image

### CODE REVIEW

**Comment by thePeras** [comment]
Nice, well done!

Can you just decrease the not found image a little bit and adding more bottom padding to text? The same goes for the mobile version in text. To close to the limit

**Comment by tomaspalma** [comment]
> Can you just decrease the not found image a little bit and adding more bottom padding to text? The same goes for the mobile version in text. To close to the limit

Yes, I've done that and updated the images on this PR's description. Let me know if that is better or if you want me to improve something!

**Comment by thePeras** [comment]
> Yes, I've done that and updated the images on this PR's description. Let me know if that is better or if you want me to improve something!

I think the image still too big for me. Sorry for being annoying

**Comment by tomaspalma** [comment]
Don't worry about it! I also didn't make it much smaller than it was prior to your comment xD

I've now changed it, see if it it's small enough :slightly_smiling_face:

**Review by thePeras — APPROVED** [review]

**Pull request merged**
