### PR TITLE
Changed build system from cra to vite and way to easily run in production mode

### PR DESCRIPTION
**Pull request by tomaspalma**
This PR adds vite as well as a specific `Dockerfile` for production as well as a new container in the `docker-compose.yaml` for production. Also, since we now have two possible containers that may run when we issue the `docker compose up` we have to specify the service, which can be cumbersome, so it also adds a  `dev.sh` and `prod.sh` script that turns the corresponding docker containers up.

Vite is a more modern and efficient development utility. Besides having more efficient and faster builds, it supports other cool features for development such as hot module code replacement (hmcr) which allows for example to just update the changed react component instead of a fully page reload.

Besides, the react scripts are outdated since the last update was last year. Also, removing packages needed by `react-scripts` as well as their package itself made some security vulnerabilities disappear.

### CODE REVIEW

**Comment by tomaspalma** [comment]
The version 3.0.0 in the package.json will be the version when the develop is merged with the main branch.

**Comment by thePeras** [comment]
I just have fixed something on my computer and committed.

Notice in order to make it run again, I needed to delete the `node_modules` and `package-lock.json` have started the frontend with `npm run dev`. Just commenting this for those who use `npm` commands.
I prefer using the original command than docker, which should be an option, and that's working!

A see now we are using nginx. It's already for niployments purpose? Or there is another reason?
Just one more thing, don't forget to update the `readme` with the new commands, and could be nice to explain what the others scripts do.

**Comment by tomaspalma** [comment]
When we run `npm run build`, it generates some static files, meaning it does not start running a server like the `npm run dev` command.

image

So, as `npm run build` does not start serving a server, we need a way to serve a server with the files inside the `build/` folder, which is where nginx comes in, which is also what nijobs used to do.

There are other options like the one used in the [new website's frontend](https://github.com/NIAEFEUP/website-niaefeup-frontend) which used `node` to run a server with the build files. However, as we use react and it creates an `index.html` instead of an `index.js`, we cannot use `node`.

Yes, I will update the README :slightly_smiling_face:

**Review by thePeras — APPROVED** [review]
Nice work!
✅ 🛫

**Pull request merged**
