### PR TITLE
Setup plausible and custom event for selected major

### LINKED ISSUE #241: Set up a nice analytics for the project
Maybe Swetrix or Plausible

### PR DESCRIPTION
**Pull request by thePeras**
Closes #241 

Screenshot 2024-08-07 at 23 48 10

### CODE REVIEW

**Comment by tomaspalma** [comment]
Great work :slightly_smiling_face: !

Besides the majors, can we also have statistics per faculty?

**Comment by thePeras** [comment]
> Great work 🙂 !
> 
> Besides the majors, can we also have statistics per faculty?

A new event or add the property to the same?

**Comment by tomaspalma** [comment]
> A new event or add the property to the same?

Maybe a new event

**Comment by thePeras** [comment]
> > A new event or add the property to the same?
> 
> Maybe a new event

done!

**Review by tomaspalma — APPROVED** [review]
:rocket:

**Pull request merged**
